name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main # Cambia esto si usas una rama diferente como principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # 1. Configurar repositorio
    - name: Checkout Repository
      uses: actions/checkout@v3

    # 2. Configurar Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18 # Ajusta según la versión compatible de Angular
        cache: 'npm'

    # 3. Instalar dependencias
    - name: Install Dependencies
      run: npm install --legacy-peer-deps

    # 4. Generar el build de Angular
    - name: Build Angular App
      run: npm run build -- --output-path=dist --base-href=https://gabrieldehner.github.io/devices/browser # Reemplaza "<tu-repo>" con el nombre de tu repositorio

    # 5. Desplegar en GitHub Pages
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
